export enum EventInscriptionStatus {
  ACCEPTED = "ACCEPTED",
  INCOMPLETE_MISSING_PAYMENT_AND_HOUR_VOTE = "INCOMPLETE_MISSING_PAYMENT_AND_HOUR_VOTE",
  INCOMPLETE_MISSING_HOUR_VOTE = "INCOMPLETE_MISSING_HOUR_VOTE",
  REJECTED = "REJECTED"
}
