export enum EventState {
  WAITING_FOR_PARTICIPANTS = "WAITING_FOR_PARTICIPANTS",
  READY_TO_START = "READY_TO_START",
  SOON_TO_START = "SOON_TO_START",
  IN_PROCESS = "IN_PROCESS",
  FINALIZED = "FINALIZED",
  CANCELED = "CANCELED"
}

