export enum PrivilegeName {
  SEARCH_USERS = 'SEARCH_USERS',
  BAN_USERS = 'BAN_USERS',
  UNBAN_USERS = 'UNBAN_USERS',
  REGISTER_ADMIN = 'REGISTER_ADMIN',
  READ_ADMINS = 'READ_ADMINS',
  MODIFY_ADMIN = 'MODIFY_ADMIN',
  DELETE_ADMIN = 'DELETE_ADMIN',
  GENERATE_STATISTICS = 'GENERATE_STATISTICS',
  READ_STATISTICS = 'READ_STATISTICS',
  SEARCH_EVENTS = 'SEARCH_EVENTS',
  CANCEL_EVENTS = 'CANCEL_EVENTS'
}
